name: CI

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Adjust the Java version as needed

      - name: Build and Run Spring Boot App
        run: |
          ./gradlew clean build  # Replace with your build command
          build/libs/Project-0.0.1-SNAPSHOT.jar